### PR TITLE
Sprint-01-Jackson

### PR DESCRIPTION
**Pull request by jacksonalvarez**
I'm going to make all my changes for sprint-0 onto this.

 **_Please don't pull unless U want my changes in the codebase, and you know my code works._** You know how I work, it probably doesn't compile etc.

We should have biweekly/monthly sprint plannings that all lead back to documentation on GitHub. I was thinking we each get our own pull request / branch that get pushed onto git as needed to prevent working on the same things, and getting lost on what others are working on. 

See you in class and later today.

### CODE REVIEW

**Comment by SolaceTh** [comment]
You shouldn't open a pull request unless the material is ready to be reviewed and added to the main branch. Making alternate branches for sprints is a good idea and we should do that, but we should avoid pull requests until the work on the branch is finished. Otherwise I'm good with the idea. Also, do we have a project board for keeping track of backlog?

**Comment by jacksonalvarez** [comment]
heard

**Comment by jacksonalvarez** [comment]
also Im not avopiding u or anything, broken phone. baking(new pack and
making bread), and focusing on sprites art for rest of day. I got aseprite
for the both of us. We gotta steam share but It is gas for 2d pixel art.


CORRESPOND BY APPSTATE EMAIL FOR FURTHER COMMUNICATION LMAO

**Comment by jacksonalvarez** [comment]
also joining disc

**Pull request merged**
